apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: multi-k8s-xyz-tls
spec:
    secretName: multi-k8s-xyz
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: multi-k8s.xyz
    dnsNames:
        - multi-k8s.xyz
        - www.multi-k8s.xyz
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - multi-k8s.xyz
                - www.multi-k8s.xyz