apiVersion: v1
# It would dynamically provision a PersistentVolume, with implementation dependent on the cloud provider
kind: PersistentVolumeClaim # see https://kubernetes.io/docs/concepts/storage/persistent-volumes/
metadata:
    name: database-persistent-volume-claim
spec:
    accessModes:
        - ReadWriteOnce # see https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    resources:
        requests:
            storage: 1Gi
            