apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: postgres
    template:
        metadata:
            labels:
                component: postgres
        spec:
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                    claimName: database-persistent-volume-claim
            containers:
                - name: postgres
                  image: postgres
                  ports:
                    - containerPort: 5432
                  volumeMounts:
                    - name: postgres-storage
                      mountPath: /var/lib/postgresql/database
                      subPath: postgres
                  env:
                    # setting this variable actually sets the database password
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        # the secret is defined imperatively, by executing
                        # kubectl create secret generic pgpassword --from-literal PGPASSWORD=someRandomPassword
                        # the same secret is used in server-deployment.yaml
                        secretKeyRef:
                            name: pgpassword
                            key: PGPASSWORD